biswasagro/biswasagro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('costs/', include("costs.urls")),
    path('inv/', include('inventory.urls')),
    path('bisauth/', include('bisauth.urls')),
    path('reports/',include('reports.urls'))
]

biswasagro/costs/urls.py
from django.urls import path
from . import views

app_name = 'costs'

urlpatterns = [
    # handle the `cost` table
    path('cost', views.show_cost_table, name='show_cost_table'),
    path('cost/delete/<int:row_id>', views.cost_delete_row, name='cost_delete_row'),
    path('addup_cost/<int:row_id>', views.add_update_cost, name="addup_cost"),

    # handle the `costitems` table
    path('costitems', views.show_costitems_table, name='show_costitems_table'),
    path('costitems/delete/<int:row_id>', views.costitems_delete_row, name='costitems_delete_row'),
    path('addup_costitems/<int:row_id>', views.add_update_costitems, name="addup_costitems"),

    # handle the `costpurpose` table
    path('costpurpose', views.show_costpurpose_table, name='show_costpurpose_table'),
    path('costpurpose/delete/<int:row_id>', views.costpurpose_delete_row, name='costpurpose_delete_row'),
    path('addup_costpurpose/<int:row_id>', views.add_update_costpurpose, name="addup_costpurpose"),

    # handle the `earning` table
    path('earning', views.show_earning_table, name='show_earning_table'),
    path('earning/delete/<int:row_id>', views.earning_delete_row, name='earning_delete_row'),
    path('addup_earning/<int:row_id>', views.add_update_earning, name="addup_earning"),

    # handle the `investment` table
    path('investment', views.show_investment_table, name='show_investment_table'),
    path('investment/delete/<int:row_id>', views.investment_delete_row, name='investment_delete_row'),
    path('addup_investment/<int:row_id>', views.add_update_investment, name="addup_investment"),

    # handle the `loandetails` table
    path('loandetails', views.show_loandetails_table, name='show_loandetails_table'),
    path('loandetails/delete/<int:row_id>', views.loandetails_delete_row, name='loandetails_delete_row'),
    path('addup_loandetails/<int:row_id>', views.add_update_loandetails, name="addup_loandetails"),

    # handle the `loan_providers_info` table
    path('loan_providers_info', views.show_loan_providers_info_table, name='show_loan_providers_info_table'),
    path('loan_providers_info/delete/<int:row_id>', views.loan_providers_info_delete_row,
         name='loan_providers_info_delete_row'),
    path('addup_loan_providers_info/<int:row_id>', views.add_update_loan_providers_info,
         name="addup_loan_providers_info"),

    # handle the `loan_transactions` table
    path('loan_transactions', views.show_loan_transactions_table, name='show_loan_transactions_table'),
    path('loan_transactions/delete/<int:row_id>', views.loan_transactions_delete_row,
         name='loan_transactions_delete_row'),
    path('addup_loan_transactions/<int:row_id>', views.add_update_loan_transactions,
         name="addup_loan_transactions"),

]

biswasagro/costs/forms.py
from django import forms
from django.forms import ModelForm
from .models import Cost, Costitems, Costpurpose, Earning, Investment, Loandetails, LoanTransactions, LoanProvidersInfo


class CostForm(ModelForm):
    date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'})  # Use an HTML5 date picker
    )

    class Meta:
        model = Cost
        fields = ['date', 'costcategory', 'costitems', 'buyamount', 'unit', 'cost', 'status',
                  'buyer', 'buyvoucher', 'comment',]

        labels = {
            'date': 'Date',
            'costcategory': 'Expense Account',
            'costitems': 'Product Name',
            'buyamount': 'Quantity',
            'unit': 'Unit',
            'cost': 'Cost amount',
            'buyer': 'Spender',
            'status': 'Status',
            'buyvoucher': 'Voucher',
            'comment': 'Additional Comments',
        }


class CostItemsForm(ModelForm):
    class Meta:
        model = Costitems
        fields = ['sector', 'costitems',]

        labels = {
            'sector': 'Sector',
            'costitems': 'Product'  #'Cost Items',
        }

        error_messages = {
            'costitems': {
                'unique': 'Product with this name already exists.',
            },
        }


class CostPurposeForm(ModelForm):
    class Meta:
        model = Costpurpose
        fields = ['costpurpose',]

        labels = {
            'costpurpose': 'Cost Purpose',
        }
        error_messages = {
            'costpurpose': {
                'unique': 'Cost Purpose with this name already exists.',
            },
        }


class EarningForm(ModelForm):
    date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'})  # Use an HTML5 date picker
    )

    class Meta:
        model = Earning
        fields = ['date', 'sector', 'item', 'source', 'quantity_per_unit', 'quantity',
                  'unit', 'price', 'status', 'memo', 'comment',]

        labels = {
            'date': 'Date',
            'sector': 'Sector',
            'item': 'Item',
            'source': 'Source',
            'quantity_per_unit': 'Quantity per Unit',
            'quantity': 'Quantity',
            'unit': 'Unit',
            'price': 'Price',
            'status': 'Status',
            'memo': 'Memo',
            'comment': 'Additional Comments',
        }


class InvestmentForm(ModelForm):
    date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'})  # Use an HTML5 date picker
    )

    class Meta:
        model = Investment
        fields = ['date', 'name', 'amount', 'comments',]

        labels = {
            'date': 'Date',
            'name': 'Name',
            'amount': 'Amount',
            'comments': 'Comments',
        }


class LoanDetailsForm(ModelForm):
    class Meta:
        model = Loandetails
        fields = ['investerid', 'amount', 'interestpermonth', 'conditions']

        labels = {
            'investerid': 'Investor ID',
            'amount': 'Amount',
            'interestpermonth': 'Interest per Month',
            'conditions': 'Conditions'
        }


class LoanProvidersInfoForm(ModelForm):
    class Meta:
        model = LoanProvidersInfo
        fields = ['name', 'address', 'mobile', 'refference']

        widgets = {
            'mobile': forms.TextInput(attrs={'maxlength': 20})
        }

        labels = {
            'name': 'Name',
            'address': 'Address',
            'mobile': 'Mobile',
            'refference': 'Reference'
        }


class LoanTransactionsForm(ModelForm):
    date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'})  # Use an HTML5 date picker
    )

    class Meta:
        model = LoanTransactions
        fields = ['loanid', 'investerid', 'date', 'payment', 'voucherno',]

        labels = {
            'loanid': 'Loan ID',
            'investerid': 'Investor ID',
            'date': 'Date',
            'payment': 'Payment',
            'voucherno': 'Voucher No.'
        }

biswasagro/costs/views.py
from django.shortcuts import redirect, reverse
from .models import *
from .forms import *
from common.utils import *
from common.column_mappers import *


#
# Cost Table (aka: Casual Expenses)
#
def show_cost_table(request):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return show_table(request, 'costs', 'cost', Cost, show_cost_mapper)


def cost_delete_row(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return delete_tabel_row(request, Cost, row_id)


def add_update_cost(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    #
    # populate specific template context values for this view
    #
    context = dict()

    # for expense_accounts, product_names, and units, we're only interested in the values and not the id's

    # get the expense accounts from the Sectors table and put the values in a set to get rid of potential duplicates
    expense_accounts = set(get_mapping(request, SECTOR_MAPPING).values())
    context['expense_accounts'] = expense_accounts

    # get product names (from Costitems table) and put the values in a set to get rid of potential duplicates
    product_names = set(get_mapping(request, COSTITEM_MAPPING).values())
    context['product_names'] = product_names

    # get units (from Units table) and put the values in a set to get rid of potential duplicates
    units = set(get_mapping(request, UNIT_MAPPING).values())
    context['units'] = units

    status_map = get_mapping(request, STATUS_MAPPING)
    context['status'] = status_map

    return add_update_table(request, 'costs', 'cost',
                            Cost, CostForm, row_id, {'logs', 'costitems_id'}, context, addup_cost_mapper)


#
# Cost Items Table
#
def show_costitems_table(request):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return show_table(request, 'costs', 'costitems', Costitems, show_costitems_mapper)


def costitems_delete_row(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return delete_tabel_row(request, Costitems, row_id)


def add_update_costitems(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    context = dict()

    # get the sector name from the sector id stored in the costitems table
    # dict -> k:{}
    secid_to_secname = {sec.id: sec.sector for sec in Sectors.objects.all()}  # dictionary comprehension
    context['secid_to_sec'] = secid_to_secname

    return add_update_table(request, 'costs', 'costitems',
                            Costitems, CostItemsForm, row_id, {'logs'}, context, addup_costitems_mapper)


#
# Cost Purpose Table
#
def show_costpurpose_table(request):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return show_table(request, 'costs', 'costpurpose', Costpurpose)


def costpurpose_delete_row(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return delete_tabel_row(request, Costpurpose, row_id)


def add_update_costpurpose(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    context = dict()
    return add_update_table(request, 'costs', 'costpurpose',
                            Costpurpose, CostPurposeForm, row_id, set(), context)


#
# Earning Table
#
def show_earning_table(request):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return show_table(request, 'costs', 'earning', Earning, show_earning_mapper)


def earning_delete_row(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return delete_tabel_row(request, Earning, row_id)


def add_update_earning(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    context = dict()

    # status pull-down
    context['status'] = get_mapping(request, STATUS_MAPPING)

    # sectors pull-down
    context['sectors'] = get_mapping(request, SECTOR_MAPPING)

    # items pull-down
    context['items'] = get_mapping(request, ITEMS_MAPPING)

    # sources pull-down
    context['sources'] = get_mapping(request, SOURCE_MAPPING)

    # units pull-down
    context['units'] = get_mapping(request, UNIT_MAPPING)

    return add_update_table(request, 'costs', 'earning',
                            Earning, EarningForm, row_id, {'logs'}, context, addup_earning_mapper)


#
# Investment Table
#
def show_investment_table(request):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return show_table(request, 'costs', 'investment', Investment, show_investment_mapper)


def investment_delete_row(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return delete_tabel_row(request, Investment, row_id)


def add_update_investment(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    context = dict()
    return add_update_table(request, 'costs', 'investment',
                            Investment, InvestmentForm, row_id, {'logs'}, context)


#
# Loandetails Table
#
def show_loandetails_table(request):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return show_table(request, 'costs', 'loandetails', Loandetails)


def loandetails_delete_row(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return delete_tabel_row(request, Loandetails, row_id)


def add_update_loandetails(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    context = dict()
    return add_update_table(request, 'costs', 'loandetails',
                            Loandetails, LoanDetailsForm, row_id, {'loanid', 'logs'}, context)


#
# Loan Providers Info Table
#
def show_loan_providers_info_table(request):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return show_table(request, 'costs', 'loan_providers_info', LoanProvidersInfo)


def loan_providers_info_delete_row(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return delete_tabel_row(request, LoanProvidersInfo, row_id)


def add_update_loan_providers_info(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    context = dict()
    return add_update_table(request, 'costs', 'loan_providers_info',
                            LoanProvidersInfo, LoanProvidersInfoForm, row_id, {'investerid', 'logs'}, context)


#
# Loan Transactions Table
#
def show_loan_transactions_table(request):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return show_table(request, 'costs', 'loan_transactions', LoanTransactions,
                      show_loan_transactions_mapper)


def loan_transactions_delete_row(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return delete_tabel_row(request, LoanTransactions, row_id)


def add_update_loan_transactions(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    context = dict()
    return add_update_table(request, 'costs', 'loan_transactions',
                            LoanTransactions, LoanTransactionsForm, row_id, set(), context)

biswasagro/costs/templates/add_update_cost.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Expenses Entry
{% endblock %}

{% block main-content %}

<div class="form-container">
    <div class="form-box">
        <h2>{{heading}}</h2>
            <form action="{% url 'costs:addup_cost' row_id=row_id %}" method="post">
                {% csrf_token %}
                <label for="{{ form.date.id_for_label }}">{{ form.date.label }}:</label>
                {{ form.date }}
                {{ form.date.errors }}

                <label for="{{ form.costcategory.id_for_label}}">{{form.costcategory.label}}:</label>
                <select name="{{form.costcategory.name}}" id="{{ form.costcategory.id_for_label}}">
                    {% for exp_acct in expense_accounts %}
                      {% if request.session.orig.costcategory == exp_acct %}
                         <option value="{{ exp_acct }}" selected>{{ exp_acct }}</option>
                      {% else %}
                         <option value="{{ exp_acct }}">{{ exp_acct }}</option>
                      {% endif %}
                    {% endfor %}
                </select>
                {{ form.costcategory.errors }}

                <label for="{{ form.costitems.id_for_label}}">{{form.costitems.label}}:</label>
                <select name="{{form.costitems.name}}" id="{{form.costitems.id_for_label}}">
                    {% for prod_name in product_names %}
                      {% if request.session.orig.costitems == prod_name %}
                       <option value="{{ prod_name }}" selected>{{ prod_name }}</option>
                      {% else %}
                       <option value="{{ prod_name }}">{{ prod_name }}</option>
                      {% endif %}
                    {% endfor %}
                </select>
                {{ form.costitems.errors }}

                <label for="{{ form.buyamount.id_for_label}}">{{form.buyamount.label}}:</label>
                {{ form.buyamount }}
                {{ form.buyamount.errors }}

                <label for="{{ form.unit.id_for_label}}">{{form.unit.label}}:</label>
                <select name="{{form.unit.name}}" id="{{ form.unit.id_for_label}}">
                    {% for unit in units %}
                      {% if request.session.orig.unit == unit %}
                      <option value="{{ unit }}" selected>{{ unit }}</option>
                    {% else %}
                      <option value="{{ unit }}">{{ unit }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
                {{ form.unit.errors }}

                <label for="{{ form.cost.id_for_label}}">{{form.cost.label}}:</label>
                {{ form.cost }}
                {{ form.cost.errors }}

                <label for="{{ form.buyer.id_for_label}}">{{form.buyer.label}}:</label>
                {{ form.buyer }}
                {{ form.buyer.errors }}

                <label for="{{ form.status.id_for_label}}">{{form.status.label}}</label>
                <select name="{{form.status.name}}" id="{{ form.status.id_for_label}}">
                    {% for stat_id, stat_val in status.items %}
                      {% if request.session.orig.status == stat_id %}
                         <option value="{{stat_id}}" selected>{{stat_val}}</option>
                      {% else %}
                         <option value="{{stat_id}}">{{stat_val}}</option>
                      {% endif %}
                    {% endfor %}
                </select>
                {{ form.status.errors }}

                <label for="{{ form.buyvoucher.id_for_label}}">{{form.buyvoucher.label}}:</label>
                {{ form.buyvoucher }}
                {{ form.buyvoucher.errors }}

                <label for="{{ form.comment.id_for_label}}">{{form.comment.label}}:</label>
                {{ form.comment }}
                {{ form.comment.errors }}

            <div class="button-group">
                <button type="button" onclick="history.back()" class="cancel-btn">Cancel</button>
                <button type="submit" class="save-btn">Save</button>
            </div>
</form>
</div>

{% endblock %}

biswasagro/costs/templates/add_update_costitems.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Product Entry
{% endblock %}

{% block main-content %}
<div class="form-container">
    <div class="form-box">
        <h2>{{heading}}</h2>
            <form action="{% url 'costs:addup_costitems' row_id=row_id %}" method="post">
                {% csrf_token %}
                <label for="{{ form.sector.id_for_label }}">{{ form.sector.label}}</label>
                <select name="{{ form.sector.name}}" id="{{ form.sector.id_for_label }}">
                    {%  for secid, sec in secid_to_sec.items %}
                      {% if request.session.orig.sector == secid %}
                         <option value="{{secid}}" selected>{{ sec }}</option>
                      {% else %}
                         <option value="{{secid}}">{{ sec }}</option>
                      {% endif %}
                    {% endfor %}
                </select>
                {{ form.sector.errors }}

                <label for="{{ form.costitems.id_for_label }}">{{ form.costitems.label }}:</label>
                {{ form.costitems }}
                {{ form.costitems.errors }}

            <div class="button-group">
                <button type="button" onclick="history.back()" class="cancel-btn">Cancel</button>
                <button type="submit" class="save-btn">Save</button>
            </div>
</form>
</div>

{% endblock %}

biswasagro/costs/templates/add_update_costpurpose.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Cost Purpose Entry
{% endblock %}

{% block main-content %}
<div class="form-container">
    <div class="form-box">
        <h2>{{heading}}</h2>
            <form action="{% url 'costs:addup_costpurpose' row_id=row_id %}" method="post">
                {% csrf_token %}
                <label for="{{ form.costpurpose.id_for_label }}">{{ form.costpurpose.label }}:</label>
                {{ form.costpurpose }}
                {{ form.costpurpose.errors }}

            <div class="button-group">
                <button type="button" onclick="history.back()" class="cancel-btn">Cancel</button>
                <button type="submit" class="save-btn">Save</button>
            </div>
</form>
</div>

{% endblock %}

biswasagro/costs/templates/add_update_earning.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Earning Entry
{% endblock %}

{% block main-content %}
<div class="form-container">
    <div class="form-box">
        <h2>{{heading}}</h2>
            <form action="{% url 'costs:addup_earning' row_id=row_id %}" method="post">
                {% csrf_token %}
                <label for="{{ form.date.id_for_label }}">{{ form.date.label }}:</label>
                {{ form.date }}
                {{ form.date.errors }}

                <label for="{{ form.status.id_for_label}}">{{form.status.label}}:</label>
                <select name="{{form.status.name}}" id="{{ form.status.id_for_label}}">
                    {% for stat_id, stat_name in status.items %}
                      {% if request.session.orig.status == stat_id %}
                         <option value="{{ stat_id }}" selected>{{ stat_name }}</option>
                      {% else %}
                         <option value="{{ stat_id }}">{{ stat_name }}</option>
                      {% endif %}
                    {% endfor %}
                </select>
                {{ form.status.errors }}

                <label for="{{ form.sector.id_for_label }}">{{ form.sector.label }}:</label>
                <select name="{{form.sector.name}}" id="{{ form.sector.id_for_label }}">
                    {% for sec_id, sec_name in sectors.items %}
                      {% if request.session.orig.sector == sec_id %}
                         <option value="{{ sec_id }}" selected>{{ sec_name }}</option>
                      {% else %}
                         <option value="{{ sec_id }}">{{ sec_name }}</option>
                      {% endif %}
                    {% endfor %}
                </select>
                {{ form.sector.errors }}

                <label for="{{ form.item.id_for_label }}">{{ form.item.label }}:</label>
                <select name="{{form.item.name}}" id="{{ form.item.id_for_label }}">
                    {% for item_id, item_name in items.items %}
                      {% if request.session.orig.item == item_id %}
                         <option value="{{ item_id }}" selected>{{ item_name }}</option>
                      {% else %}
                         <option value="{{ item_id }}">{{ item_name }}</option>
                      {% endif %}
                    {% endfor %}
                </select>
                {{ form.item.errors }}

                <label for="{{ form.source.id_for_label }}">{{ form.source.label }}:</label>
                <select name="{{form.source.name}}" id="{{ form.source.id_for_label }}">
                    {% for source_id, source_name in sources.items %}
                      {% if request.session.orig.source == source_id %}
                         <option value="{{ source_id }}" selected>{{ source_name }}</option>
                      {% else %}
                         <option value="{{ source_id }}">{{ source_name }}</option>
                      {% endif %}
                    {% endfor %}
                </select>
                {{ form.source.errors }}

                <label for="{{ form.quantity_per_unit.id_for_label }}">{{ form.quantity_per_unit.label }}:</label>
                {{ form.quantity_per_unit }}
                {{ form.quantity_per_unit.errors }}

                <label for="{{ form.quantity.id_for_label }}">{{ form.quantity.label }}:</label>
                {{ form.quantity }}
                {{ form.quantity.errors }}

                <label for="{{ form.unit.id_for_label }}">{{ form.unit.label }}:</label>
                <select name="{{form.unit.name}}" id="{{ form.unit.id_for_label }}">
                    {% for unit_id, unit_name in units.items %}
                      {% if request.session.orig.unit == unit_id %}
                         <option value="{{ unit_id }}" selected>{{ unit_name }}</option>
                      {% else %}
                         <option value="{{ unit_id }}">{{ unit_name }}</option>
                      {% endif %}
                    {% endfor %}
                </select>
                {{ form.unit.errors }}

                <label for="{{ form.price.id_for_label }}">{{ form.price.label }}:</label>
                {{ form.price }}
                {{ form.price.errors }}

                <label for="{{ form.memo.id_for_label }}">{{ form.memo.label }}:</label>
                {{ form.memo }}
                {{ form.memo.errors }}

                <label for="{{ form.comment.id_for_label }}">{{ form.comment.label }}:</label>
                {{ form.comment }}
                {{ form.comment.errors }}

            <div class="button-group">
                <button type="button" onclick="history.back()" class="cancel-btn">Cancel</button>
                <button type="submit" class="save-btn">Save</button>
            </div>
</form>
</div>

{% endblock %}

biswasagro/costs/templates/add_update_loan_providers_info.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Loan Providers Info Entry
{% endblock %}

{% block main-content %}
<div class="form-container">
    <div class="form-box">
        <h2>{{heading}}</h2>
            <form action="{% url 'costs:addup_loan_providers_info' row_id=row_id %}" method="post">
                {% csrf_token %}
                <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
                {{ form.name }}
                {{ form.name.errors }}

                <label for="{{ form.address.id_for_label }}">{{ form.address.label }}:</label>
                {{ form.address }}
                {{ form.address.errors }}

                <label for="{{ form.mobile.id_for_label }}">{{ form.mobile.label }}:</label>
                {{ form.mobile }}
                {{ form.mobile.errors }}

                <label for="{{ form.refference.id_for_label }}">{{ form.refference.label }}:</label>
                {{ form.refference }}
                {{ form.refference.errors }}

            <div class="button-group">
                <button type="button" onclick="history.back()" class="cancel-btn">Cancel</button>
                <button type="submit" class="save-btn">Save</button>
            </div>
</form>
</div>

{% endblock %}

biswasagro/costs/templates/add_update_loan_transactions.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Loan Transactions Entry
{% endblock %}

{% block main-content %}
<div class="form-container">
    <div class="form-box">
        <h2>{{heading}}</h2>
            <form action="{% url 'costs:addup_loan_transactions' row_id=row_id %}" method="post">
                {% csrf_token %}
                <label for="{{ form.date.id_for_label }}">{{ form.date.label }}:</label>
                {{ form.date }}
                {{ form.date.errors }}

                <label for="{{ form.loanid.id_for_label }}">{{ form.loanid.label }}:</label>
                {{ form.loanid }}
                {{ form.loanid.errors }}

                <label for="{{ form.investerid.id_for_label }}">{{ form.investerid.label }}:</label>
                {{ form.investerid }}
                {{ form.investerid.errors }}

                <label for="{{ form.payment.id_for_label }}">{{ form.payment.label }}:</label>
                {{ form.payment }}
                {{ form.payment.errors }}

                <label for="{{ form.voucherno.id_for_label }}">{{ form.voucherno.label }}:</label>
                {{ form.voucherno }}
                {{ form.voucherno.errors }}

            <div class="button-group">
                <button type="button" onclick="history.back()" class="cancel-btn">Cancel</button>
                <button type="submit" class="save-btn">Save</button>
            </div>
</form>
</div>

{% endblock %}

biswasagro/costs/templates/add_update_loandetails.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Loan Details Entry
{% endblock %}

{% block main-content %}
<div class="form-container">
    <div class="form-box">
        <h2>{{heading}}</h2>
            <form action="{% url 'costs:addup_loandetails' row_id=row_id %}" method="post">
                {% csrf_token %}
                <label for="{{ form.investerid.id_for_label }}">{{ form.investerid.label }}:</label>
                {{ form.investerid }}
                {{ form.investerid.errors }}

                <label for="{{ form.amount.id_for_label }}">{{ form.amount.label }}:</label>
                {{ form.amount }}
                {{ form.amount.errors }}

                <label for="{{ form.interestpermonth.id_for_label }}">{{ form.interestpermonth.label }}:</label>
                {{ form.interestpermonth }}
                {{ form.interestpermonth.errors }}

                <label for="{{ form.conditions.id_for_label }}">{{ form.conditions.label }}:</label>
                {{ form.conditions }}
                {{ form.conditions.errors }}

            <div class="button-group">
                <button type="button" onclick="history.back()" class="cancel-btn">Cancel</button>
                <button type="submit" class="save-btn">Save</button>
            </div>
</form>
</div>

{% endblock %}