biswasagro/bisauth/urls.py
from django.urls import path
from . import views

app_name = 'bisauth'

urlpatterns = [
    # handle login and register
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('change_pass/', views.change_password, name='change_password'),
    path('admin_ch_pass/<int:row_id>', views.admin_ch_password, name='admin_ch_pass'),
    path('logout/', views.logout, name='logout'),

    # handle the `roles` table
    path('roles', views.show_roles_table, name='show_roles_table'),
    path('addup_roles/<int:row_id>', views.add_update_roles, name="addup_roles"),
    path('roles/delete/<int:row_id>', views.roles_delete_row, name='roles_delete_row'),

    # handle the `usersinfo` table
    path('usersinfo', views.show_usersinfo_table, name='show_usersinfo_table'),
    path('addup_usersinfo/<int:row_id>', views.add_update_usersinfo, name="addup_usersinfo"),
    path('usersinfo/delete/<int:row_id>', views.usersinfo_delete_row, name='usersinfo_delete_row'),

    # handle the `salary` table
    path('salary', views.show_salary_table, name='show_salary_table'),
    path('addup_salary/<int:row_id>', views.add_update_salary, name="addup_salary"),
    path('salary/delete/<int:row_id>', views.salary_delete_row, name='salary_delete_row'),

    # handle the `staff` table
    path('staff', views.show_staff_table, name='show_staff_table'),
    path('addup_staff/<int:row_id>', views.add_update_staff, name="addup_staff"),
    path('staff/delete/<int:row_id>', views.staff_delete_row, name='staff_delete_row'),

    # handle the `staffs` table
    path('staffs', views.show_staffs_table, name='show_staffs_table'),
    path('addup_staffs/<int:row_id>', views.add_update_staffs, name="addup_staffs"),
    path('staffs/delete/<int:row_id>', views.staffs_delete_row, name='staffs_delete_row'),

]

biswasagro/biswasagro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('costs/', include("costs.urls")),
    path('inv/', include('inventory.urls')),
    path('bisauth/', include('bisauth.urls')),
    path('reports/',include('reports.urls'))
]

biswasagro/costs/urls.py
from django.urls import path
from . import views

app_name = 'costs'

urlpatterns = [
    # handle the `cost` table
    path('cost', views.show_cost_table, name='show_cost_table'),
    path('cost/delete/<int:row_id>', views.cost_delete_row, name='cost_delete_row'),
    path('addup_cost/<int:row_id>', views.add_update_cost, name="addup_cost"),

    # handle the `costitems` table
    path('costitems', views.show_costitems_table, name='show_costitems_table'),
    path('costitems/delete/<int:row_id>', views.costitems_delete_row, name='costitems_delete_row'),
    path('addup_costitems/<int:row_id>', views.add_update_costitems, name="addup_costitems"),

    # handle the `costpurpose` table
    path('costpurpose', views.show_costpurpose_table, name='show_costpurpose_table'),
    path('costpurpose/delete/<int:row_id>', views.costpurpose_delete_row, name='costpurpose_delete_row'),
    path('addup_costpurpose/<int:row_id>', views.add_update_costpurpose, name="addup_costpurpose"),

    # handle the `earning` table
    path('earning', views.show_earning_table, name='show_earning_table'),
    path('earning/delete/<int:row_id>', views.earning_delete_row, name='earning_delete_row'),
    path('addup_earning/<int:row_id>', views.add_update_earning, name="addup_earning"),

    # handle the `investment` table
    path('investment', views.show_investment_table, name='show_investment_table'),
    path('investment/delete/<int:row_id>', views.investment_delete_row, name='investment_delete_row'),
    path('addup_investment/<int:row_id>', views.add_update_investment, name="addup_investment"),

    # handle the `loandetails` table
    path('loandetails', views.show_loandetails_table, name='show_loandetails_table'),
    path('loandetails/delete/<int:row_id>', views.loandetails_delete_row, name='loandetails_delete_row'),
    path('addup_loandetails/<int:row_id>', views.add_update_loandetails, name="addup_loandetails"),

    # handle the `loan_providers_info` table
    path('loan_providers_info', views.show_loan_providers_info_table, name='show_loan_providers_info_table'),
    path('loan_providers_info/delete/<int:row_id>', views.loan_providers_info_delete_row,
         name='loan_providers_info_delete_row'),
    path('addup_loan_providers_info/<int:row_id>', views.add_update_loan_providers_info,
         name="addup_loan_providers_info"),

    # handle the `loan_transactions` table
    path('loan_transactions', views.show_loan_transactions_table, name='show_loan_transactions_table'),
    path('loan_transactions/delete/<int:row_id>', views.loan_transactions_delete_row,
         name='loan_transactions_delete_row'),
    path('addup_loan_transactions/<int:row_id>', views.add_update_loan_transactions,
         name="addup_loan_transactions"),

]

biswasagro/bisauth/views.py
from django.contrib.auth.hashers import make_password
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from common.utils import *
from common.column_mappers import *

# define the order of the User Roles from the least access to most, we use this when creating a new
# user. The preferred role level is the one that has the least amount of access.
ROLE_LEVELS = ['User', 'Operator', 'Manager', 'Admin']


#
# Login
#
def login(request):

    if 'user' in request.session:
        # this means there is a user logged in
        # render the home page
        return render(request, 'home.html', {})

    context = dict()
    if request.method == 'GET':
        form = LoginForm()
    elif request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data

            userinfo = Usersinfo.objects.filter(username=cleaned_data.get('username'))
            user = None
            if userinfo.exists():
                user = userinfo[0]
                # add the user to the session and render the home page
                # we need to know what the user's role is
                request.session['user'] = {'id': user.id,
                                           'username': user.username,
                                           'role': user.role}
                return render(request, 'home.html', {})

        else:  # form is invalid for ANY reason
            context['form'] = form  # re-render form with errors
            return render(request, 'login.html', context)

    context['form'] = form
    return render(request, 'login.html', context)


def logout(request):
    # remove everything from the session
    request.session.clear()
    # if 'user' in request.session:
    #     del request.session['user']
    #     remove_all_mappings(request)
    return redirect('home')


#
# Register a new user
#
def register(request):

    if request.method == 'GET':
        form = RegistrationForm()
    elif request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            cleaned_data = form.cleaned_data
            username = cleaned_data.get('username')
            password = cleaned_data.get('password')
            hashed_password = make_password(password)
            user.password = hashed_password
            user.mobile = cleaned_data.get('mobile')

            db_known_roles = get_mapping(request, ROLE_MAPPING).values()
            # we will default to giving a new user the lowest level of access to the system, this value
            # could be changed by an Admin or Manager later
            # we loop over the ROLE_LEVELS until we find one that is defined in the database, if none was found
            # this means the database values were changed or removed, so we give an ID with the highest value, but
            # we set the is_active flag to 0 meaning the user is inactive and can not access the site until the
            # role is fixed by an Admin
            this_users_role = 'Unknown'
            for role_name in ROLE_LEVELS:
                if this_users_role != 'Unknown':
                    break
                for r_name in db_known_roles:
                    if role_name == r_name:
                        # we found a match
                        user.role = role_name
                        user.isactive = 1  # default to making the new user active
                        this_users_role = role_name
                        break
            if this_users_role == 'Unknown':
                # this is an exceptional case and should never happen if the database is set up correctly
                # in this case (we didn't find any roles which were listed in the ROLE_LEVELS list) we
                # assign a Role of "Unknown" and we set the isActive flag to inactive so that the user can not
                # log in until an Admin fixes this situation (by changing the role to an valid value).
                user.role = this_users_role
                user.isactive = 0  # make this user inactive

            user.save()

            # see if we were able to create the user, if so we'll redirect to the login page if not
            # we render the registration form again
            if user:
                # present the login form and indicate that the account was created
                context = dict()
                form = LoginForm()
                context['new_user'] = username
                context['form'] = form
                return render(request, 'login.html', context)

    context = dict()
    context['form'] = form
    return render(request, 'register.html', context)


def change_password(request):
    """This function handles the case where a user is changing their own password"""

    if request.method == 'GET':
        form = ChangePasswordForm()
    elif request.method == 'POST':
        form = ChangePasswordForm(request.POST)

    if form.is_valid():
        # process the password change here
        cleaned_data = form.cleaned_data
        userinfo = Usersinfo.objects.filter(username=cleaned_data.get('username'))
        user = None
        if userinfo.exists():
            user = userinfo[0]

            # we know we have valid data from the form (and now it's in cleaned_data) so we just save the
            # new_password on the user object and save to the DB
            new_password = cleaned_data.get('new_password')
            hashed_password = make_password(new_password)
            user.password = hashed_password
            user.save()
            # present the login form and indicate that the password was changed
            context = dict()
            form = LoginForm()
            context['password_updated'] = True
            context['username'] = cleaned_data.get('username')
            context['form'] = form
            return render(request, 'login.html', context)
    else:
        # render the form again with errors
        return render(request, 'change_pass.html', {'form': form})


def admin_ch_password(request, row_id):
    """This function handles the case where an Admin is changing the password of another user"""

    if 'user' not in request.session or request.session['user']['role'] != 'Admin':
        # this means if we're not logged in or the logged-in user is NOT an Admin therefore this functionality
        # is not allowed so redirect the user to the home page
        return render(request, 'home.html', {})

    if request.method == 'GET':
        # get the username from the row_id
        model_obj = get_object_or_404(Usersinfo, pk=row_id)  # get the object to update
        # set the username from the model_obj on the form
        form = AdminChPasswordForm(initial={'username': model_obj.username})
        context = dict()
        context['form'] = form
        context['username'] = model_obj.username
        context['row_id'] = row_id
        return render(request, 'admin_ch_pass.html', context)
    elif request.method == 'POST':

        form = AdminChPasswordForm(request.POST)

        if form.is_valid():
            # process the password change here
            cleaned_data = form.cleaned_data

            userinfo = Usersinfo.objects.filter(username=cleaned_data.get('username'))
            # we know this user exists so it's safe to index the 0th item
            user = userinfo[0]

            # we also know we have valid data from the form (and now it's in cleaned_data) so we just save the
            # new_password on the user object and save to the DB
            new_password = cleaned_data.get('new_password')
            hashed_password = make_password(new_password)
            user.password = hashed_password
            user.save()

            msg_text = f"password changed for user {cleaned_data.get('username')}"
            messages.add_message(request, messages.INFO, msg_text, extra_tags='temporary')
            return redirect('bisauth:show_usersinfo_table')
        else:
            # render the form again with errors
            model_obj = get_object_or_404(Usersinfo, pk=row_id)  # get the object to update
            context = dict()
            context['username'] = model_obj.username
            context['form'] = form
            context['row_id'] = row_id
            return render(request, 'admin_ch_pass.html', context)


#
# roles Table
#
def show_roles_table(request):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return show_table(request, 'bisauth', 'roles', Roles)


def roles_delete_row(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return delete_tabel_row(request, Roles, row_id)


def add_update_roles(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    context = dict()
    return add_update_table(request, 'bisauth', 'roles',
                            Roles, RolesForm, row_id, set(), context)


#
# usersinfo Table
#
def show_usersinfo_table(request):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return show_table(request, 'bisauth', 'usersinfo', Usersinfo, show_usersinfo_mapper)


def usersinfo_delete_row(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    return delete_tabel_row(request, Usersinfo, row_id)


def add_update_usersinfo(request, row_id):
    is_in = 'user' in request.session
    if not is_in:
        return redirect('bisauth:login')

    skip_set = {'password', 'created_at', 'updated_at'}
    context = dict()
    context['is_active'] = IS_ACTIVE  # a dict
    context['roles'] = get_mapping(request, ROLE_MAPPING)  # a dict

biswasagro/bisauth/templates/add_update_staffs.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Staffs Entry
{% endblock %}

{% block main-content %}
<div class="form-container">
    <div class="form-box">
        <h2>{{heading}}</h2>
            <form action="{% url 'bisauth:addup_staffs' row_id=row_id %}" method="post">
                {% csrf_token %}
                <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
                {{ form.name }}
                {{ form.name.errors }}

                <label for="{{ form.designation.id_for_label }}">{{ form.designation.label }}:</label>
                {{ form.designation }}
                {{ form.designation.errors }}

                <label for="{{ form.address.id_for_label }}">{{ form.address.label }}:</label>
                {{ form.address }}
                {{ form.address.errors }}

                <label for="{{ form.mobile.id_for_label }}">{{ form.mobile.label }}:</label>
                {{ form.mobile }}
                {{ form.mobile.errors }}

            <div class="button-group">
                <button type="button" onclick="history.back()" class="cancel-btn">Cancel</button>
                <button type="submit" class="save-btn">Save</button>
            </div>
</form>
</div>

{% endblock %}

biswasagro/bisauth/templates/add_update_usersinfo.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Users Entry
{% endblock %}

{% block main-content %}
<div class="form-container">
    <div class="form-box">
        <h2>{{heading}}</h2>
            <form action="{% url 'bisauth:addup_usersinfo' row_id=row_id %}" method="post">
                {% csrf_token %}
                <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
                {{ form.name }}
                {{ form.name.errors }}

                <label for="{{ form.username.id_for_label }}">{{ form.username.label }}:</label>
                {{ form.username }}
                {{ form.username.errors }}

                <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
                {{ form.email }}
                {{ form.email.errors }}

                <label for="{{ form.mobile.id_for_label }}">{{ form.mobile.label }}:</label>
                {{ form.mobile }}
                {{ form.mobile.errors }}

                <label for="{{ form.role.id_for_label }}">{{ form.role.label }}:</label>
                <select name="{{form.role.name}}" id="{{ form.role.id_for_label }}">
                    {% for role_id, role_name in roles.items %}
                      {% if request.session.orig.role == role_name %}
                         <option value="{{ role_name }}" selected>{{ role_name }}</option>
                      {% else %}
                         <option value="{{ role_name }}">{{ role_name }}</option>
                      {% endif %}
                    {% endfor %}
                </select>
                {{ form.role.errors }}

                <label for="{{ form.isactive.id_for_label }}">{{ form.isactive.label }}:</label>
                <select name="{{form.isactive.name}}" id="{{ form.isactive.id_for_label }}">
                    {% for active_id, active_txt in is_active.items %}
                      {% if request.session.orig.isactive == active_id %}
                         <option value="{{ active_id }}" selected>{{ active_txt }}</option>
                      {% else %}
                         <option value="{{ active_id }}">{{ active_txt }}</option>
                      {% endif %}
                    {% endfor %}
                </select>
                {{ form.isactive.errors }}

            <div class="button-group">
                <button type="button" onclick="history.back()" class="cancel-btn">Cancel</button>
                <button type="submit" class="save-btn">Save</button>
            </div>
</form>
</div>

{% endblock %}

biswasagro/bisauth/templates/admin_ch_pass.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Change User's Password - BiswasAgro</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/support.js' %}" defer></script>
</head>
<body>
    <div class="register-container">
        <div class="form-box">
            <h2>Change User's Password</h2>
            <form action="{% url 'bisauth:admin_ch_pass' row_id=row_id %}" method="post">
                {% csrf_token %}

                <label for="{{ form.username.id_for_label }}">{{ form.username.label }}:</label>
                <input type="text" value="{{ username }}" id="{{ form.username.id_for_label }}" disabled>
                {{ form.username.errors }}

                <input type="hidden" name="username" value="{{ username }}">

                <label for="{{ form.new_password.id_for_label }}">{{ form.new_password.label }}:</label>
                {{ form.new_password }}
                {{ form.new_password.errors }}

                <label for="{{ form.confirm_password.id_for_label }}">{{ form.confirm_password.label }}:</label>
                {{ form.confirm_password }}
                {{ form.confirm_password.errors }}

                 {% if form.non_field_errors %}  {# Display non-field errors #}
                <ul class="errorlist">
                    {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}

                <div class="button-group">
                    <button type="button" onclick="history.back()" class="cancel-btn">Cancel</button>
                    <button type="submit" class="save-btn">Save</button>
                </div>

            </form>
        </div>
    </div>
</body>
</html>

biswasagro/bisauth/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login - BiswasAgro</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/support.js' %}" defer></script>
</head>
<body>
    <div class="register-container">
        <div class="form-box">
            <h2>BiswasAgro Login</h2>
            <form action="{% url 'bisauth:login' %}" method="post">
                {% csrf_token %}

                <label for="{{ form.username.id_for_label }}">{{ form.username.label }}:</label>
                {{ form.username }}
                {{ form.username.errors }}

                <label for="{{ form.password.id_for_label }}">{{ form.password.label }}:</label>
                {{ form.password }}
                {{ form.password.errors }}

                 {% if form.non_field_errors %}  {# Display non-field errors #}
                <ul class="errorlist">
                    {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}

                {% if new_user %}
                <ul class="new-user">
                    <li>account created for username: {{ new_user }}</li>
                </ul>
                {% endif %}

                <div>
                    <button type="submit" class="save-btn">Login</button>
                    <p>Don't have an account? <a href="{% url 'bisauth:register' %}">Register a new account</a></p>
                </div>

        </div>
    </div>
</body>
</html>

biswasagro/bisauth/templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register - BiswasAgro</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/support.js' %}" defer></script>
</head>
<body>
    <div class="register-container">
        <div class="form-box">
            <h2>Register a new account</h2>
            <form action="{% url 'bisauth:register' %}" method="post">
                {% csrf_token %}

                <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
                {{ form.name }}
                {{ form.name.errors }}

                <label for="{{ form.username.id_for_label }}">{{ form.username.label }}:</label>
                {{ form.username }}
                {{ form.username.errors }}

                <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
                {{ form.email }}
                {{ form.email.errors }}

                <label for="{{ form.mobile.id_for_label }}">{{ form.mobile.label }}:</label>
                {{ form.mobile }}
                {{ form.mobile.errors }}

                <label for="{{ form.password.id_for_label }}">{{ form.password.label }}:</label>
                {{ form.password }}
                {{ form.password.errors }}

                <label for="{{ form.confirm_password.id_for_label }}">{{ form.confirm_password.label }}:</label>
                {{ form.confirm_password }}
                {{ form.confirm_password.errors }}

                 {% if form.non_field_errors %}  {# Display non-field errors #}
                <ul class="errorlist">
                    {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}

                <div class="button-group">
                    <button type="button" onclick="history.back()" class="cancel-btn">Cancel</button>
                    <button type="submit" class="save-btn">Save</button>
                </div>

            </form>
        </div>
    </div>
</body>
</html>

biswasagro/bisauth/templates/roles_landing.html
{% extends 'layout.html' %}

{% block title %}
Cost Table
{% endblock %}

{% block main-content %}
        <div class="table-wrapper">
            <h2>Roles Table</h2>
            <div class="table-container">
                <table>
                        <tr>
                            <th>ID</th>
                            <th>Role</th>
                            {% if request.session.user.role == 'Admin' or request.session.user.role == 'Manager' %}
                            <th>Actions</th>
                            {% endif %}
                        </tr>
                    <tbody>
                    {% for a_page in page_objs %}
                        <tr>
                            <td>{{a_page.id}}</td>
                            <td>{{a_page.role}}</td>
                            {% if request.session.user.role == 'Admin' or request.session.user.role == 'Manager' %}
                            <td>
                                <a href="{% url 'bisauth:addup_roles' row_id=a_page.id %}" class="action-link">Edit</a>
                                {% endif %}
                                {% if request.session.user.role == 'Admin' %}
                                | <a href="#" class="action-link delete-table-entry" table-id="bisauth/roles" data-id="{{a_page.id}}">Delete</a>
                            </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

{% include 'pagination_control.html' %}

{% endblock %}

biswasagro/bisauth/templates/salary_landing.html
{% extends 'layout.html' %}

{% block title %}
Salary Table
{% endblock %}

{% block main-content %}
        <div class="table-wrapper">
            <h2>Salary</h2>
            <div class="table-container">
                <table>
                        <tr>
                            <th>Date</th>
                            <th>Purpose</th>
                            <th>Reason</th>
                            <th>Qty</th>
                            <th>Rate</th>
                            <th>Total</th>
                            <th>Personnel</th>
                            <th>Voucher</th>
                            <th>Status</th>
                            <th>Comments</th>
                            {% if request.session.user.role == 'Admin' or request.session.user.role == 'Manager' %}
                            <th>Actions</th>
                            {% endif %}
                        </tr>
                    <tbody>
                    {% for a_page in page_objs %}
                        <tr>
                            <td>{{a_page.date}}</td>
                            <td>{{a_page.purpose}}</td>
                            <td>{{a_page.reason}}</td>
                            <td>{{a_page.quantity}}</td>
                            <td>{{a_page.rate}}</td>
                            <td>{{a_page.total}}</td>
                            <td>{{a_page.personel}}</td>
                            <td>{{a_page.voucher}}</td>
                            <td>{{a_page.status}}</td>
                            <td>{{a_page.comment}}</td>
                            {% if request.session.user.role == 'Admin' or request.session.user.role == 'Manager' %}
                            <td>
                                <a href="{% url 'bisauth:addup_salary' row_id=a_page.id %}" class="action-link">Edit</a>
                            {% endif %}
                            {% if request.session.user.role == 'Admin' %}
                                 | <a href="#" class="action-link delete-table-entry" table-id="bisauth/salary" data-id="{{a_page.id}}">Delete</a>
                            </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

{% include 'pagination_control.html' %}

<!--CL we can put a search selection here            -->
<!--<label for="c_search">Choose search</label>-->
<!--<select name="c_search" id="c_search">-->
<!--    <option value="date">date</option>-->
<!--    <option value="id">id</option>-->
<!--</select>-->
<!-- CL end search selection-->

{% endblock %}

biswasagro/bisauth/templates/usersinfo_landing.html
{% extends 'layout.html' %}

{% block title %}
Users Table
{% endblock %}

{% block main-content %}
        <div class="table-wrapper">
            <h2>Users Table</h2>
            <div class="table-container">
                <table>
                        <tr>
                            <th>Name</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Mobile</th>
                            <th>Role</th>
                            <th>Is Active</th>
                            {% if request.session.user.role == 'Admin' or request.session.user.role == 'Manager' %}
                            <th>Actions</th>
                            {% endif %}
                            {% if request.session.user.role == 'Admin' %}
                            <th>Password</th>
                            {% endif %}
                        </tr>
                    <tbody>
                    {% for a_page in page_objs %}
                        <tr>
                            <td>{{ a_page.name }}</td>
                            <td>{{ a_page.username }}</td>
                            <td>{{ a_page.email }}</td>
                            <td>{{ a_page.mobile }}</td>
                            <td>{{ a_page.role }}</td>
                            <td>{{ a_page.isactive }}</td>
                            {% if request.session.user.role == 'Admin' or request.session.user.role == 'Manager' %}
                            <td>
                                <a href="{% url 'bisauth:addup_usersinfo' row_id=a_page.id %}" class="action-link">Edit</a>
                                {% endif %}
                                {% if request.session.user.role == 'Admin' %}
                                | <a href="#" class="action-link delete-table-entry" table-id="bisauth/usersinfo" data-id="{{a_page.id}}">Delete</a>
                            </td>
                            {% endif %}
                            {% if request.session.user.role == 'Admin' %}
                            <td><a href="{% url 'bisauth:admin_ch_pass' row_id=a_page.id %}" class="action-link">Change</a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

{% include 'pagination_control.html' %}

{% endblock %}