biswasagro/bisauth/urls.py
from django.urls import path
from . import views

app_name = 'bisauth'

urlpatterns = [
    # handle login and register
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('change_pass/', views.change_password, name='change_password'),
    path('admin_ch_pass/<int:row_id>', views.admin_ch_password, name='admin_ch_pass'),
    path('logout/', views.logout, name='logout'),

    # handle the `roles` table
    path('roles', views.show_roles_table, name='show_roles_table'),
    path('addup_roles/<int:row_id>', views.add_update_roles, name="addup_roles"),
    path('roles/delete/<int:row_id>', views.roles_delete_row, name='roles_delete_row'),

    # handle the `usersinfo` table
    path('usersinfo', views.show_usersinfo_table, name='show_usersinfo_table'),
    path('addup_usersinfo/<int:row_id>', views.add_update_usersinfo, name="addup_usersinfo"),
    path('usersinfo/delete/<int:row_id>', views.usersinfo_delete_row, name='usersinfo_delete_row'),

    # handle the `salary` table
    path('salary', views.show_salary_table, name='show_salary_table'),
    path('addup_salary/<int:row_id>', views.add_update_salary, name="addup_salary"),
    path('salary/delete/<int:row_id>', views.salary_delete_row, name='salary_delete_row'),

    # handle the `staff` table
    path('staff', views.show_staff_table, name='show_staff_table'),
    path('addup_staff/<int:row_id>', views.add_update_staff, name="addup_staff"),
    path('staff/delete/<int:row_id>', views.staff_delete_row, name='staff_delete_row'),

    # handle the `staffs` table
    path('staffs', views.show_staffs_table, name='show_staffs_table'),
    path('addup_staffs/<int:row_id>', views.add_update_staffs, name="addup_staffs"),
    path('staffs/delete/<int:row_id>', views.staffs_delete_row, name='staffs_delete_row'),

]

biswasagro/biswasagro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('costs/', include("costs.urls")),
    path('inv/', include('inventory.urls')),
    path('bisauth/', include('bisauth.urls')),
    path('reports/',include('reports.urls'))
]

biswasagro/costs/urls.py
from django.urls import path
from . import views

app_name = 'costs'

urlpatterns = [
    # handle the `cost` table
    path('cost', views.show_cost_table, name='show_cost_table'),
    path('cost/delete/<int:row_id>', views.cost_delete_row, name='cost_delete_row'),
    path('addup_cost/<int:row_id>', views.add_update_cost, name="addup_cost"),

    # handle the `costitems` table
    path('costitems', views.show_costitems_table, name='show_costitems_table'),
    path('costitems/delete/<int:row_id>', views.costitems_delete_row, name='costitems_delete_row'),
    path('addup_costitems/<int:row_id>', views.add_update_costitems, name="addup_costitems"),

    # handle the `costpurpose` table
    path('costpurpose', views.show_costpurpose_table, name='show_costpurpose_table'),
    path('costpurpose/delete/<int:row_id>', views.costpurpose_delete_row, name='costpurpose_delete_row'),
    path('addup_costpurpose/<int:row_id>', views.add_update_costpurpose, name="addup_costpurpose"),

    # handle the `earning` table
    path('earning', views.show_earning_table, name='show_earning_table'),
    path('earning/delete/<int:row_id>', views.earning_delete_row, name='earning_delete_row'),
    path('addup_earning/<int:row_id>', views.add_update_earning, name="addup_earning"),

    # handle the `investment` table
    path('investment', views.show_investment_table, name='show_investment_table'),
    path('investment/delete/<int:row_id>', views.investment_delete_row, name='investment_delete_row'),
    path('addup_investment/<int:row_id>', views.add_update_investment, name="addup_investment"),

    # handle the `loandetails` table
    path('loandetails', views.show_loandetails_table, name='show_loandetails_table'),
    path('loandetails/delete/<int:row_id>', views.loandetails_delete_row, name='loandetails_delete_row'),
    path('addup_loandetails/<int:row_id>', views.add_update_loandetails, name="addup_loandetails"),

    # handle the `loan_providers_info` table
    path('loan_providers_info', views.show_loan_providers_info_table, name='show_loan_providers_info_table'),
    path('loan_providers_info/delete/<int:row_id>', views.loan_providers_info_delete_row,
         name='loan_providers_info_delete_row'),
    path('addup_loan_providers_info/<int:row_id>', views.add_update_loan_providers_info,
         name="addup_loan_providers_info"),

    # handle the `loan_transactions` table
    path('loan_transactions', views.show_loan_transactions_table, name='show_loan_transactions_table'),
    path('loan_transactions/delete/<int:row_id>', views.loan_transactions_delete_row,
         name='loan_transactions_delete_row'),
    path('addup_loan_transactions/<int:row_id>', views.add_update_loan_transactions,
         name="addup_loan_transactions"),

]

biswasagro/inventory/urls.py
from django.urls import path
from . import views

# app_name = 'inventory'
app_name = 'inv'


urlpatterns = [
    # handle the `fishbuy` table
    path('fishbuy', views.show_fishbuy_table, name='show_fishbuy_table'),
    path('addup_fishbuy/<int:row_id>', views.add_update_fishbuy, name="addup_fishbuy"),
    path('fishbuy/delete/<int:row_id>', views.fishbuy_delete_row, name='fishbuy_delete_row'),

    # handle the `fishtype` table
    path('fishtype', views.show_fishtype_table, name='show_fishtype_table'),
    path('addup_fishtype/<int:row_id>', views.add_update_fishtype, name="addup_fishtype"),
    path('fishtype/delete/<int:row_id>', views.fishtype_delete_row, name='fishtype_delete_row'),

    # handle the `items` table
    path('items', views.show_items_table, name='show_items_table'),
    path('addup_items/<int:row_id>', views.add_update_items, name="addup_items"),
    path('items/delete/<int:row_id>', views.items_delete_row, name='items_delete_row'),

    # handle the `land` table
    path('land', views.show_land_table, name='show_land_table'),
    path('addup_land/<int:row_id>', views.add_update_land, name="addup_land"),
    path('land/delete/<int:row_id>', views.land_delete_row, name='land_delete_row'),

    # handle the `sectors` table
    path('sectors', views.show_sectors_table, name='show_sectors_table'),
    path('addup_sectors/<int:row_id>', views.add_update_sectors, name="addup_sectors"),
    path('sectors/delete/<int:row_id>', views.sectors_delete_row, name='sectors_delete_row'),

    # handle the `units` table
    path('units', views.show_units_table, name='show_units_table'),
    path('addup_units/<int:row_id>', views.add_update_units, name="addup_units"),
    path('units/delete/<int:row_id>', views.units_delete_row, name='units_delete_row'),

    # handle the `dailyworks` table
    path('dailyworks', views.show_dailyworks_table, name='show_dailyworks_table'),
    path('addup_dailyworks/<int:row_id>', views.add_update_dailyworks, name="addup_dailyworks"),
    path('dailyworks/delete/<int:row_id>', views.dailyworks_delete_row, name='dailyworks_delete_row'),

    # handle the `fooddistribution` table
    path('fooddist', views.show_fooddistribution_table, name='show_fooddistribution_table'),
    path('addup_fooddistribution/<int:row_id>', views.add_update_fooddistribution, name="addup_fooddistribution"),
    path('fooddistribution/delete/<int:row_id>', views.fooddistribution_delete_row, name='fooddistribution_delete_row'),

    # handle the `mousa` table
    path('mousa', views.show_mousa_table, name='show_mousa_table'),
    path('addup_mousa/<int:row_id>', views.add_update_mousa, name="addup_mousa"),
    path('mousa/delete/<int:row_id>', views.mousa_delete_row, name='mousa_delete_row'),

    # handle the `mousaname` table
    path('mousaname', views.show_mousaname_table, name='show_mousaname_table'),
    path('addup_mousaname/<int:row_id>', views.add_update_mousaname, name="addup_mousaname"),
    path('mousaname/delete/<int:row_id>', views.mousaname_delete_row, name='mousaname_delete_row'),

    # handle the `sources` table
    path('sources', views.show_sources_table, name='show_sources_table'),
    path('addup_sources/<int:row_id>', views.add_update_sources, name="addup_sources"),
    path('sources/delete/<int:row_id>', views.sources_delete_row, name='sources_delete_row'),

    # handle the `units` table
    path('units', views.show_units_table, name='show_units_table'),
    path('addup_units/<int:row_id>', views.add_update_units, name="addup_units"),
    path('units/delete/<int:row_id>', views.units_delete_row, name='units_delete_row'),

    # handle the `term` table
    path('term', views.show_term_table, name='show_term_table'),
    path('addup_term/<int:row_id>', views.add_update_term, name="addup_term"),
    path('term/delete/<int:row_id>', views.term_delete_row, name='term_delete_row'),

]

biswasagro/reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns = [
    path('landing', views.reports_landing, name='landing'),
    path('daily/<str:str_date>', views.daily, name='daily'),
    path('monthly/<str:str_date>', views.monthly, name='monthly'),
    path('annual/<str:str_date>', views.annual, name='annual'),
    path('finacc', views.financial_accounting, name='finacc'),
    path('fish_details', views.fish_count_details, name='fish_cnt_details'),
    path('land_report/<str:source>', views.land_report, name='land_report'),
    path('disp_fish', views.display_fish_chart, name='disp_fish'),
    path('gen_fish/<str:str_date>', views.generate_fish_chart, name='gen_fish'),
    path('disp_earning', views.display_earnings, name='disp_earn'),
    path('gen_earn_plt/<str:plt_source>', views.gen_earn_plt, name='gen_earn_plt'),
]

biswasagro/templates/add_update_confirmation.html
{% extends 'layout.html' %}

{% block title %}
Add/Update Confirmation
{% endblock %}


{% block main-content %}

<div class="confirmation-table-wrapper">
    <h2>{{heading}}</h2>
    <div class="confirmation-table-container">
                <table>
                        <tr>
                            <th>Column Name</th>
                            {% if new_entry %}
                                <th>Value</th>
                            {% else %}
                                <th>Original Value</th>
                                <th>Changed Value</th>
                            {% endif %}
                        </tr>
                    <tbody>
                    {% for field_data_map in field_data %}
                        <tr>
                            <td>{{ field_data_map.col_name }}</td>
                            {% if new_entry %}
                                <td class="orig-value">{{ field_data_map.orig_value }}</td>
                            {% else %}
                                <td class="orig-value">{{ field_data_map.orig_value }}</td>
                                <td class="new-value">{{ field_data_map.new_value }}</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
    </div>
        <div class="pagination-container">
        <div class="pagination-left">
            <a href="{{ next_url }}" class="pagination-button">Return</a>
        </div>
    </div>

</div>


{% endblock %}

biswasagro/templates/home.html
{% extends 'layout.html' %}
{% block title %}
    BiswasAgro - Home
{% endblock %}


{% block main-content %}
<div class="home-container">
    <div class="home-box">
        <h2>Welcome to BiswasAgro</h2>
        <p>Get started by clicking on any of the options on the left.</p>
    </div>
</div>

<!--CL: start-->
<p>The current user's role: {{request.session.user.role}} &nbsp;</p>
<!--CL: end-->
{% endblock %}

biswasagro/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/support.js' %}" defer></script>
</head>
<body>
<div class="dashboard-container">
    {% include "sidebar.html" %}

    {% block main-content %}
    {% endblock %}
</div>

{% if addModal %}
    {% include "modal_control.html" %}
{% endif %}

</body>
</html>

biswasagro/templates/modal_control.html
    <div id="delete-modal" class="modal">
        <div class="modal-content">
            <h3>Are you sure you want to delete this entry?</h3>
            <button class="modal-btn cancel-btn">No</button>
            <button class="modal-btn confirm-delete-btn">Yes</button>
        </div>
    </div>

biswasagro/templates/pagination_control.html
            <div class="pagination-container">
                <div class="pagination-left">
                    {% if not skipAddButton  %}
                        <a href="{% url add_url row_id=0 %}" class="pagination-button">Add New Entry</a>
                    {% endif %}
                    {% if messages %}
                      {% for message in messages %}
                       {% if 'temporary' in message.tags %}
                           <p class="new-user">{{ message }}</p>
                       {% endif %}
                      {% endfor %}
                    {% endif %}
                </div>
                <div class=pagination-right">
                    {% if page_objs.has_previous %}
                       <a href="?page=1" class="pagination-button">&laquo; First</a>
                       <a href="?page={{ page_objs.previous_page_number }}" class="pagination-button">Previous</a>
                    {% else %}
                       <a href="?page=1" class="pagination-button disabled">&laquo; First</a>
                       <a href="?page=1" class="pagination-button disabled">Previous</a>
                    {% endif %}
                    page {{page_objs.number}} of {{page_objs.paginator.num_pages}}
                    {% if page_objs.has_next %}
                       <a href="?page={{ page_objs.next_page_number }}" class="pagination-button">Next</a>
                       <a href="?page={{ page_objs.paginator.num_pages}}" class="pagination-button">Last &raquo;</a>
                    {% else %}
                       <a href="?page=1" class="pagination-button disabled">Next</a>
                       <a href="?page=1" class="pagination-button disabled">Last &raquo;</a>
                    {% endif %}
                </div>
            </div>

biswasagro/templates/sidebar.html
        <div class="sidebar">
            <a href="{% url 'home' %}" class="sidebar-button">Home</a>
            <a href="{% url 'costs:show_cost_table' %}" class="sidebar-button">Casual Expenses</a>
            <a href="{% url 'costs:show_costitems_table' %}" class="sidebar-button">Products</a>
            <a href="{% url 'costs:show_costpurpose_table' %}" class="sidebar-button">Cost Purpose Table</a>
            <a href="{% url 'inv:show_dailyworks_table' %}" class="sidebar-button">Daily Works</a>
            <a href="{% url 'costs:show_earning_table' %}" class="sidebar-button">Earnings</a>
            <a href="{% url 'inv:show_fishbuy_table' %}" class="sidebar-button">Fish Purchase</a>
            <a href="{% url 'inv:show_fishtype_table' %}" class="sidebar-button">Fishtype</a>
            <a href="{% url 'inv:show_fooddistribution_table' %}" class="sidebar-button">Food Distribution</a>
            <a href="{% url 'costs:show_investment_table' %}" class="sidebar-button">Investment</a>
            <a href="{% url 'inv:show_items_table' %}" class="sidebar-button">Items</a>
            <a href="{% url 'inv:show_land_table' %}" class="sidebar-button">Land</a>
            <a href="{% url 'costs:show_loandetails_table' %}" class="sidebar-button">Loan Details</a>
            <a href="{% url 'costs:show_loan_providers_info_table' %}" class="sidebar-button">Loan Providers Info</a>
            <a href="{% url 'costs:show_loan_transactions_table' %}" class="sidebar-button">Loan Transactions</a>
            <a href="{% url 'inv:show_mousa_table' %}" class="sidebar-button">Hari Transaction</a>
            <a href="{% url 'inv:show_mousaname_table' %}" class="sidebar-button">Mousa Name</a>
            <a href="{% url 'bisauth:show_salary_table' %}" class="sidebar-button">Salary</a>
            <a href="{% url 'inv:show_sectors_table' %}" class="sidebar-button">Sectors</a>
            <a href="{% url 'inv:show_sources_table' %}" class="sidebar-button">Sources</a>
            <a href="{% url 'bisauth:show_staff_table' %}" class="sidebar-button">Staff</a>
            <a href="{% url 'bisauth:show_staffs_table' %}" class="sidebar-button">Staffs</a>
            <a href="{% url 'inv:show_units_table' %}" class="sidebar-button">Units</a>
            <a href="{% url 'bisauth:show_usersinfo_table' %}" class="sidebar-button">Users</a>
            <a href="{% url 'bisauth:show_roles_table' %}" class="sidebar-button">Roles</a>
            <a href="{% url 'inv:show_term_table' %}" class="sidebar-button">Term</a>
            <a href="{% url 'reports:landing' %}" class="sidebar-button">Reports</a>
            <a href="{% url 'bisauth:logout' %}" class="sidebar-button">Log Out</a>
        </div>