biswasagro/biswasagro/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('costs/', include("costs.urls")),
    path('inv/', include('inventory.urls')),
    path('bisauth/', include('bisauth.urls')),
    path('reports/',include('reports.urls'))
]

biswasagro/costs/urls.py
from django.urls import path
from . import views

app_name = 'costs'

urlpatterns = [
    # handle the `cost` table
    path('cost', views.show_cost_table, name='show_cost_table'),
    path('cost/delete/<int:row_id>', views.cost_delete_row, name='cost_delete_row'),
    path('addup_cost/<int:row_id>', views.add_update_cost, name="addup_cost"),

    # handle the `costitems` table
    path('costitems', views.show_costitems_table, name='show_costitems_table'),
    path('costitems/delete/<int:row_id>', views.costitems_delete_row, name='costitems_delete_row'),
    path('addup_costitems/<int:row_id>', views.add_update_costitems, name="addup_costitems"),

    # handle the `costpurpose` table
    path('costpurpose', views.show_costpurpose_table, name='show_costpurpose_table'),
    path('costpurpose/delete/<int:row_id>', views.costpurpose_delete_row, name='costpurpose_delete_row'),
    path('addup_costpurpose/<int:row_id>', views.add_update_costpurpose, name="addup_costpurpose"),

    # handle the `earning` table
    path('earning', views.show_earning_table, name='show_earning_table'),
    path('earning/delete/<int:row_id>', views.earning_delete_row, name='earning_delete_row'),
    path('addup_earning/<int:row_id>', views.add_update_earning, name="addup_earning"),

    # handle the `investment` table
    path('investment', views.show_investment_table, name='show_investment_table'),
    path('investment/delete/<int:row_id>', views.investment_delete_row, name='investment_delete_row'),
    path('addup_investment/<int:row_id>', views.add_update_investment, name="addup_investment"),

    # handle the `loandetails` table
    path('loandetails', views.show_loandetails_table, name='show_loandetails_table'),
    path('loandetails/delete/<int:row_id>', views.loandetails_delete_row, name='loandetails_delete_row'),
    path('addup_loandetails/<int:row_id>', views.add_update_loandetails, name="addup_loandetails"),

    # handle the `loan_providers_info` table
    path('loan_providers_info', views.show_loan_providers_info_table, name='show_loan_providers_info_table'),
    path('loan_providers_info/delete/<int:row_id>', views.loan_providers_info_delete_row,
         name='loan_providers_info_delete_row'),
    path('addup_loan_providers_info/<int:row_id>', views.add_update_loan_providers_info,
         name="addup_loan_providers_info"),

    # handle the `loan_transactions` table
    path('loan_transactions', views.show_loan_transactions_table, name='show_loan_transactions_table'),
    path('loan_transactions/delete/<int:row_id>', views.loan_transactions_delete_row,
         name='loan_transactions_delete_row'),
    path('addup_loan_transactions/<int:row_id>', views.add_update_loan_transactions,
         name="addup_loan_transactions"),

]

biswasagro/reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns = [
    path('landing', views.reports_landing, name='landing'),
    path('daily/<str:str_date>', views.daily, name='daily'),
    path('monthly/<str:str_date>', views.monthly, name='monthly'),
    path('annual/<str:str_date>', views.annual, name='annual'),
    path('finacc', views.financial_accounting, name='finacc'),
    path('fish_details', views.fish_count_details, name='fish_cnt_details'),
    path('land_report/<str:source>', views.land_report, name='land_report'),
    path('disp_fish', views.display_fish_chart, name='disp_fish'),
    path('gen_fish/<str:str_date>', views.generate_fish_chart, name='gen_fish'),
    path('disp_earning', views.display_earnings, name='disp_earn'),
    path('gen_earn_plt/<str:plt_source>', views.gen_earn_plt, name='gen_earn_plt'),
]

biswasagro/reports/models.py
from django.db import models

# Create your models here.

biswasagro/reports/forms.py
from django import forms
from django.forms import Form
from datetime import date

# Human-readable format for Dates
DISPLAY_FMT = '%d-%m-%Y'


class DateSelectorForm(Form):
    # Use an HTML5 date picker
    date = forms.DateField(label="Date", widget=forms.DateInput(attrs={'type': 'date'}))


class YearMonthForm(Form):
    year = forms.CharField(label="Year", required=True)
    month = forms.CharField(label='Month', required=True)


class YearForm(Form):
    year = forms.CharField(label="Year", required=True)


class ToFromDateSelectorForm(Form):
    # Use an HTML5 date pickers
    fr_date = forms.DateField(label="Date From", widget=forms.DateInput(attrs={'type': 'date'}))
    to_date = forms.DateField(label="To", widget=forms.DateInput(attrs={'type': 'date'}))

biswasagro/reports/views.py
import re
import io
import base64
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from datetime import date, datetime
from dateutil.relativedelta import relativedelta
from collections import defaultdict
from costs.models import Cost, Earning
from bisauth.models import Salary
from inventory.models import Fishbuy, Mousa, Land
from .forms import DateSelectorForm, YearMonthForm, YearForm, ToFromDateSelectorForm
from common.utils import get_dates_in_month, get_now
from common.column_mappers import *

# add font for Bengali characters
plt.rcParams['font.family'] = ['DejaVu Sans', 'Noto Serif Bengali']

# expected: 2025-04 [April 2025]
# m.group(1) -> year
# m.group(2) -> month (zero padded)
MONTHLY_RE = re.compile(r"(\d{4})-(\d{2})")

# expected: 23-04-2025 [April 23 2025]
# m.group(1) -> day (zero padded)
# m.group(2) -> month (zero padded)
# m.group(3) -> year
DAILY_RE = re.compile(r"(\d{2})-(\d{2})-(\d{4})")

MONTH_NAMES = {
    '01': 'January',
    '02': 'February',
    '03': 'March',
    '04': 'April',
    '05': 'May',
    '06': 'June',
    '07': 'July',
    '08': 'August',
    '09': 'September',
    '10': 'October',
    '11': 'November',
    '12': 'December',
}

# Human-readable format for Dates
DISPLAY_FMT = '%d-%m-%Y'

# Database (ISO 8601) format required for lookups on the database
DB_FMT = '%Y-%m-%d'

PLOT_BAR_COLOR = '#b0a787'
PLOT_BODY_COLOR = '#d9d9d9'


def reports_landing(request):
    if 'user' not in request.session:
        # no reports allowed if you're not logged in!
        return redirect('bisauth:login')

    return render(request, 'reports_landing.html', {})


def daily(request, str_date):
    """
    Generate the daily report, it should include, costs, fishbuy, mousa, and salary for debits and
    earnings for credits
    """

    if 'user' not in request.session:
        # no reports allowed if you're not logged in!
        return redirect('bisauth:login')

    context = dict()
    right_now = get_now(to_str=False)

    month_word = None
    day_word = None
    if request.method == 'GET':
        if str_date == 'now':
            # this means to use right now as the timestamp
            month_word = right_now.strftime('%B')
            month_numb_str = right_now.strftime('%m')
            year_str = right_now.strftime('%Y')
            day_str = right_now.strftime('%d')
        else:
            # we need to parse the passed in str_date to know which date we're actually interested in
            m = DAILY_RE.search(str_date)
            if m:
                day_str = m.group(1)
                month_numb_str = m.group(2)
                year_str = m.group(3)
                # get the day_word and month_word by creating a datetime object and then changing its format
                dt = datetime.strptime(str_date, '%d-%m-%Y')
                month_word = dt.strftime('%B')
                day_word = dt.strftime('%a')
            else:
                # a bad string was passed to us so just use "now" as a fall-back
                day_word = right_now.strftime('%a')
                day_str = right_now.strftime('%d')
                month_word = right_now.strftime('%B')
                month_numb_str = right_now.strftime('%m')
                year_str = right_now.strftime('%Y')

        # we need year-month-day for initializing a date field
        date_str = f"{year_str}-{month_numb_str}-{day_str}"

        initial_data = {'date': date_str}  # allow the form constructor parse the string
        form = DateSelectorForm(initial=initial_data, data=initial_data)
    else:
        # POST
        form = DateSelectorForm(request.POST)

    if not form.is_valid():
        context['form'] = form
        template_name = 'daily_report.html'
        return render(request, template_name, context)

    # from here we know we have a valid form (date)
    cleaned_data = form.cleaned_data
    form_date = cleaned_data['date']  # datetime.date object

    year_str = form_date.strftime('%Y')
    month_numb_str = form_date.strftime('%m')
    day_str = form_date.strftime('%d')

    if not month_word:
        month_word = form_date.strftime('%B')

    if not day_word:
        day_word = form_date.strftime('%a')

    date_query_str = f"{year_str}-{month_numb_str}-{day_str}"

    #
    # Debits (from cost, fishbuy, mousa, and salary tables)
    #

    # get the data from cost table
    rows_from_cost = list(Cost.objects.filter(date=date_query_str))
    context['rows_from_cost'] = rows_from_cost
    context['num_rows_from_cost'] = len(rows_from_cost)
    context['num_rows_from_cost_plus_1'] = len(rows_from_cost) + 1

    cost_total = 0.00
    for row in rows_from_cost:
        # reformat the cost values by converting them to strings with commas (for display in the template)
        cost_total += row.cost
        row.cost = f"{row.cost:,.2f}"  # we convert to a string just for display
    context['cost_total'] = f"{cost_total:,.2f}"

    # get the data from the fishbuy table
    rows_from_fishbuy = list(Fishbuy.objects.filter(date=date_query_str))
    context['rows_from_fishbuy'] = rows_from_fishbuy
    context['num_rows_from_fishbuy'] = len(rows_from_fishbuy)
    context['num_rows_from_fishbuy_plus_1'] = len(rows_from_fishbuy) + 1

    fishbuy_total = 0.0
    for row in rows_from_fishbuy:
        # reformat the price values by converting them to strings with commas (for display in the template)
        fishbuy_total += row.price
        row.price = f"{row.price:,.2f}"  # we convert to a string just for display
    context['fishbuy_total'] = f"{fishbuy_total:,.2f}"

    # get the data from the salary table
    rows_from_salary = list(Salary.objects.filter(date=date_query_str))
    context['rows_from_salary'] = rows_from_salary
    context['num_rows_from_salary'] = len(rows_from_salary)
    context['num_rows_from_salary_plus_1'] = len(rows_from_salary) + 1

    salary_total = 0.0
    for row in rows_from_salary:
        # reformat the total values by converting them to strings with commas (for display in the template)
        salary_total += row.total
        row.total = f"{row.total:,.2f}"  # we convert to a string just for display
    context['salary_total'] = f"{salary_total:,.2f}"

    # get the data from the mousa table
    rows_from_mousa = list(Mousa.objects.filter(date=date_query_str))
    context['rows_from_mousa'] = rows_from_mousa
    context['num_rows_from_mousa'] = len(rows_from_mousa)
    context['num_rows_from_mousa_plus_1'] = len(rows_from_mousa) + 1

    mousa_total = 0.0
    for row  in rows_from_mousa:
        # reformat the amount values by converting them to strings with commas (for display in the template)
        mousa_total += row.amount
        row.amount = f"{row.amount:,.2f}"
    context['mousa_total'] = mousa_total

    costs_grand_total = cost_total + fishbuy_total + salary_total + mousa_total
    context['costs_grand_total'] = f"{costs_grand_total:,.2f}"

    #
    # Earnings (from earnings table)
    #
    rows_from_earning = list(Earning.objects.filter(date=date_query_str))
    context['rows_from_earning'] = rows_from_earning
    context['num_rows_from_earning'] = len(rows_from_earning)
    context['num_rows_from_earning_plus_1'] = len(rows_from_earning) + 1

    earning_total = 0.0
    # we need to do the mappings lookups and reformat the price values for display
    sector_mapping = get_mapping(request, SECTOR_MAPPING)
    item_mapping = get_mapping(request, ITEMS_MAPPING)
    source_mapping = get_mapping(request, SOURCE_MAPPING)
    for row in rows_from_earning:
        # reformat the price values by converting them to strings with commas (for display in the template)
        earning_total += row.price
        row.sector = sector_mapping[row.sector]
        row.item = item_mapping[row.item]
        row.source = source_mapping[row.source]
        row.price = f"{row.price:,.2f}"
    context['earning_total'] = f"{earning_total:,.2f}"

    context['form'] = form
    context['right_now'] = get_now(to_str=True)
    context['month_word'] = month_word
    context['year'] = int(year_str)
    context['month'] = month_numb_str
    context['day_str'] = day_str
    context['day_word'] = day_word

    template_name = 'daily_report.html'
    return render(request, template_name, context)


def monthly(request, str_date):
    """Generate the monthly report of costs and expenses"""

    if 'user' not in request.session:
        # no reports allowed if you're not logged in!
        return redirect('bisauth:login')

    context = dict()
    # we always want to report on when the report was made: "now"
    right_now = get_now(to_str=False)

    month_word = None
    if request.method == 'GET':
        if str_date == 'now':
            # this means to use right now as the timestamp
            month_word = right_now.strftime('%B')
            month_numb_str = right_now.strftime('%m')
            year_str = right_now.strftime('%Y')
        else:
            # we need to parse the passed in str_date to know which month we're actually interested in
            m = MONTHLY_RE.search(str_date)
            if m:
                year_str = m.group(1)
                month_numb_str = m.group(2)
                # get the month_word by creating a datetime object and then changing its format
                dt = datetime.strptime(str_date, '%Y-%m')
                month_word = dt.strftime('%B')
            else:
                # a bad string was passed to us so just use "now" as a fall-back
                month_word = right_now.strftime('%B')
                month_numb_str = right_now.strftime('%m')
                year_str = right_now.strftime('%Y')

        initial_data = {'year': year_str, 'month': month_numb_str}
        form = YearMonthForm(initial=initial_data, data=initial_data)

    else:

biswasagro/reports/templates/annual_report.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Annual Report
{% endblock %}

{% block main-content %}

{% include 'top_nav.html' %}

<div class="content-area">
   <div class="report-content">
           <form id="date_form" method="post" action="{% url 'reports:annual' str_date='none' %}">
               {% csrf_token %}
                <label for="{{ form.year.id_for_label }}">{{ form.year.label }}:</label>
                <select id="{{ form.year.id_for_label }}" name="{{form.year.name}}" >
                   {% for year_val in year_select %}
                        <option value="{{ year_val }}" {% if year_val == year %}selected{% endif %}>{{ year_val }}</option>
                   {% endfor %}
                </select>
                {{ form.year.errors }}

               <button type="submit">Search</button>
           </form>

      <h2>Annual Report for {{ year }}</h2>
      <p>report generated at: {{ right_now }}</p>
       {% if value_dict|length > 0 %}
      <table>
        <tr>
          <th>Month</th>
          <th>Costs</th>
          <th>Earnings</th>
        </tr>
          {% for m_str, v_lst in value_dict.items %}
          <tr>

              <td><a href="{% url 'reports:monthly' str_date=m_str %}" class="report-link">{{v_lst.0}}</a></td>
              <td>{{v_lst.1}}</td>
              <td>{{v_lst.2}}</td>
          </tr>
          {% endfor %}
          <!-- add the totals  -->
          <tr>
              <td class="totals">Totals</td>
              <td class="total_values">{{total_costs}}</td>
              <td class="total_values">{{total_earnings}}</td>
          </tr>
      </table>
       {% else %}
       <h2>No values to display for this year</h2>
       {% endif %}

</div>
</div>
{% endblock %}

biswasagro/reports/templates/earning_charts.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Earning Charts
{% endblock %}

{% block main-content %}

{% include 'top_nav.html' %}

<div class="content-area">
   <div class="report-content">
           <form id="date_form" method="post" action="{% url 'reports:disp_earn' %}">
               {% csrf_token %}
                <label for="{{ form.fr_date.id_for_label }}">{{ form.fr_date.label }}:</label>
               {{ form.fr_date }}
               {{ form.fr_date.errors }}

                <label for="{{ form.to_date.id_for_label }}">{{ form.to_date.label }}:</label>
               {{ form.to_date }}
               {{ form.to_date.errors }}

               <button type="submit">Search</button>
           </form>

<br/>
       <h2>Price per Item by Source from {{fr_date_str}} to {{to_date_str}}</h2>
<p>report generated at: {{ right_now }}</p>

       <br/>
       <br/>

<!-- North -->
       {% if has_data_dict.North %}
       <img src="{% url 'reports:gen_earn_plt' plt_source='North' %}" alt="North earning plot">
       {% else %}
       <p>No data for North for this timespan</p>
       {% endif %}

       <br/>
       <br/>

<!-- South -->
       {% if has_data_dict.South %}
       <img src="{% url 'reports:gen_earn_plt' plt_source='South' %}" alt="South earning plot">
       {% else %}
       <p>No data for South for this timespan</p>
       {% endif %}

       <br/>
       <br/>

<!-- East -->
       {% if has_data_dict.East %}
       <img src="{% url 'reports:gen_earn_plt' plt_source='East' %}" alt="East earning plot">
       {% else %}
       <p>No data for East for this timespan</p>
       {% endif %}

       <br/>
       <br/>

<!-- West -->
       {% if has_data_dict.West %}
       <img src="{% url 'reports:gen_earn_plt' plt_source='West' %}" alt="West earning plot">
       {% else %}
       <p>No data for West for this timespan</p>
       {% endif %}

       <br/>
       <br/>

       <!-- Uzzal -->
       {% if has_data_dict.Uzzal %}
       <img src="{% url 'reports:gen_earn_plt' plt_source='Uzzal' %}" alt="Uzzal earning plot">
       {% else %}
       <p>No data for Uzzal for this timespan</p>
       {% endif %}


       <br/>
</div>
</div>
{% endblock %}

biswasagro/reports/templates/finacc_report.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Financial Accounting Report
{% endblock %}

{% block main-content %}

{% include 'top_nav.html' %}

<div class="content-area">
   <div class="report-content">
           <form id="date_form" method="post" action="{% url 'reports:finacc' %}">
               {% csrf_token %}

                <label for="{{ form.fr_date.id_for_label }}">{{ form.fr_date.label }}:</label>
               {{ form.fr_date }}
               {{ form.fr_date.errors }}

                <label for="{{ form.to_date.id_for_label }}">{{ form.to_date.label }}:</label>
               {{ form.to_date }}
               {{ form.to_date.errors }}

               <button type="submit">Search</button>
           </form>

<br/>
<p>report generated at: {{ right_now }}</p>

<br/>
  <table>
    <tr>
        <th colspan="6"><h2>Unity Agro Pvt. Ltd.</h2></th>
    </tr>
    <tr>
        <td colspan="6" ><h3>Ledger Balance from {{current_start_str}} to {{current_end_str}}</h3></td>
    </tr>
<tr>
  <td colspan="3" class="report-left">Previous Debit ({{previous_start_str}} to {{previous_end_str}})</td>
  <td class="report-right">{{previous_debits}}</td>
  <td class="report-left">Final Balance</td>
  <td class="report-right">{{final_balance}}</td>
</tr>
<tr>
  <td colspan="3" class="report-left">Previous Credit ({{previous_start_str}} to {{previous_end_str}})</td>
  <td class="report-right">{{previous_credits}}</td>
  <td class="report-left">Loan</td>
  <td class="report-right">-</td>
</tr>
<tr>
  <td class="report-left">Account No.</td>
  <td class="report-left">-</td>
  <td class="report-left">Current debit</td>
  <td class="report-right">{{current_debits}}</td>
  <td class="report-left">Bank</td>
  <td class="report-right">-</td>
</tr>
<tr>
  <td class="report-left">Account No.</td>
  <td class="report-left">-</td>
  <td class="report-left">Current credit</td>
  <td class="report-right">{{current_credits}}</td>
  <td class="report-left">In Hand</td>
  <td class="report-right">-</td>
</tr>
  </table>

<br/>

       <h4>Details for selected date span: {{fr_date}} to {{to_date}}</h4>

<!-- value table -->
<table>
  <tr>
    <th>Date</th>
    <th>Debit</th>
    <th>Credit</th>
    <th>Total Debit</th>
    <th>Total Credit</th>
  </tr>
    {% for span_row in summary_data %}
    <tr>
        <td>{{span_row.0}}</td>
        <td class="report-right">{{span_row.1}}</td>
        <td class="report-right">{{span_row.2}}</td>
        <td class="report-right">{{span_row.3}}</td>
        <td class="report-right">{{span_row.4}}</td>
  </tr>
    {% endfor %}
</table>


</div>
</div>
{% endblock %}

biswasagro/reports/templates/fish_chart.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Fish Count Chart
{% endblock %}

{% block main-content %}

{% include 'top_nav.html' %}

<div class="content-area">
   <div class="report-content">
           <form id="date_form" method="post" action="{% url 'reports:disp_fish' %}">
               {% csrf_token %}
                <label for="{{ form.fr_date.id_for_label }}">{{ form.fr_date.label }}:</label>
               {{ form.fr_date }}
               {{ form.fr_date.errors }}

                <label for="{{ form.to_date.id_for_label }}">{{ form.to_date.label }}:</label>
               {{ form.to_date }}
               {{ form.to_date.errors }}

               <button type="submit">Search</button>
           </form>

<br/>
       <h2>Number of fish by Source from {{fr_date_str}} to {{to_date_str}}</h2>
<p>report generated at: {{ right_now }}</p>

<br/>

       <img src="{% url 'reports:gen_fish' str_date=db_date %}" alt="Fish quantity plot">
<br/>
</div>
</div>
{% endblock %}

biswasagro/reports/templates/monthly_report.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Monthly Report
{% endblock %}

{% block main-content %}

{% include 'top_nav.html' %}

<div class="content-area">
   <div class="report-content">
           <form id="date_form" method="post" action="{% url 'reports:monthly' str_date='none' %}">
               {% csrf_token %}
                <label for="{{ form.year.id_for_label }}">{{ form.year.label }}:</label>
                <select id="{{ form.year.id_for_label }}" name="{{form.year.name}}" >
                   {% for year_val in year_select %}
                        <option value="{{ year_val }}" {% if year_val == year %}selected{% endif %}>{{ year_val }}</option>
                   {% endfor %}
                </select>
                {{ form.year.errors }}

               <label for="{{ form.month.id_for_label }}">{{ form.month.label }}:</label>
               <select id="{{ form.month.id_for_label }}" name="{{ form.month.name }}">
                   {% for m_id, m_name in month_select.items %}
                      <option value="{{m_id}}" {% if m_id == month %}selected{% endif %}>{{m_name}}</option>
                   {% endfor %}
               </select>
               {{ form.month.errors }}

               <button type="submit">Search</button>
           </form>


      <h2>Monthly Report for {{ month_word }} {{ year }}</h2>
      <p>report generated at: {{ right_now }}</p>
       {% if value_dict|length > 0 %}
      <table>
        <tr>
          <th>Date</th>
          <th>Costs</th>
          <th>Earnings</th>
        </tr>
          {% for d_str, v_lst in value_dict.items %}
          <tr>

              <td><a href="{% url 'reports:daily' str_date=d_str %}" class="report-link">{{d_str}}</a></td>
              <td>{{v_lst.0}}</td>
              <td>{{v_lst.1}}</td>
          </tr>
          {% endfor %}
          <!-- add the totals  -->
          <tr>
              <td class="totals">Totals</td>
              <td class="total_values">{{total_costs}}</td>
              <td class="total_values">{{total_earnings}}</td>
          </tr>
      </table>
       {% else %}
       <h2>No values to display for this month</h2>
       {% endif %}

</div>
</div>
{% endblock %}

biswasagro/reports/templates/reports_landing.html
{% extends 'layout.html' %}

{% block title %}
BiswasAgro - Reports
{% endblock %}

{% block main-content %}

{% include 'top_nav.html' %}

<div id="content-container" class="content-area">

   <div class="default-content">
      <h2>Welcome to BiswasAgro Reports</h2>
      <p>Select an option from the navigation above</p>
   </div>
</div>

{% endblock %}

biswasagro/reports/templates/top_nav.html
<div class="toplevel-report">
  <nav class="top-nav">
  <!-- First row of links  -->
  <ul class="nav-row">
     <li><a href="{% url 'reports:daily' str_date='now' %}" class="nav-link">Daily Report</a></li>
     <li><a href="{% url 'reports:monthly' str_date='now' %}" class="nav-link">Monthly Report</a></li>
     <li><a href="{% url 'reports:annual' str_date='now' %}" class="nav-link">Annual Report</a></li>
     <li><a href="">Investment Report</a></li>
     <li><a href="{% url 'reports:finacc' %}" class="nav-link">Financial Accounting</a></li>
  </ul>

  <!-- Second row of links (Dropdowns) -->
  <ul class="nav-row">
     <li class="dropdown">
<!--         <a href="">Fish counting ▾</a>-->
         <p>Fish Counting ▾</p>
         <ul class="dropdown-menu">
            <li><a href="{% url 'reports:fish_cnt_details' %}">Details</a></li>
            <li><a href="">Summary</a></li>
            <li><a href="">Current fish count</a></li>
         </ul>
     </li>
     <li class="dropdown">
<!--         <a href="">Hari's report ▾</a>-->
         <p>Hari's report ▾</p>
         <ul class="dropdown-menu">
            <li><a href="">Landowner's account</a></li>
            <li><a href="">Fiscal Year 2023-24</a></li>
            <li><a href="">Fiscal Year 2024-25</a></li>
         </ul>
     </li>
     <li class="dropdown">
<!--         <a href="">Land related ▾</a>-->
         <p>Land related ▾</p>
         <ul class="dropdown-menu">
            <li><a href="{% url 'reports:land_report' source='North' %}">North</a></li>
            <li><a href="{% url 'reports:land_report' source='South' %}">South</a></li>
            <li><a href="{% url 'reports:land_report' source='East' %}">East</a></li>
            <li><a href="{% url 'reports:land_report' source='West' %}">West</a></li>
            <li><a href="{% url 'reports:land_report' source='Uzzal' %}">Uzzal</a></li>
         </ul>
     </li>
     <li class="dropdown">
<!--         <a href="">Charts ▾</a>-->
         <p>Charts ▾</p>
         <ul class="dropdown-menu">
            <li><a href="{% url 'reports:disp_fish' %}">Fish Charts</a></li>
            <li><a href="">Cost Charts</a></li>
            <li><a href="{% url 'reports:disp_earn' %}">Earning Charts</a></li>
            <li><a href="">Fishbuy Charts</a></li>
         </ul>
     </li>
   </ul>
  </nav>